// Country flag emojis - hardcoded to avoid encoding issues
const FLAGS: Record<string, string> = {
  'GR': '🇬🇷', 'IT': '🇮🇹', 'FR': '🇫🇷', 'ES': '🇪🇸',
  'PT': '🇵🇹', 'TR': '🇹🇷', 'CY': '🇨🇾', 'TH': '🇹🇭',
  'JP': '🇯🇵', 'IN': '🇮🇳', 'EG': '🇪🇬', 'JO': '🇯🇴',
  'MA': '🇲🇦', 'AE': '🇦🇪', 'MV': '🇲🇻', 'SC': '🇸🇨',
  'MU': '🇲🇺', 'TZ': '🇹🇿', 'KE': '🇰🇪', 'ZA': '🇿🇦',
  'US': '🇺🇸', 'CA': '🇨🇦', 'MX': '🇲🇽', 'BR': '🇧🇷',
  'AR': '🇦🇷', 'CO': '🇨🇴', 'PE': '🇵🇪', 'AU': '🇦🇺',
  'NZ': '🇳🇿', 'GB': '🇬🇧', 'DE': '🇩🇪', 'NL': '🇳🇱',
  'CZ': '🇨🇿', 'AT': '🇦🇹', 'CH': '🇨🇭', 'HR': '🇭🇷',
  'HU': '🇭🇺', 'PL': '🇵🇱', 'RO': '🇷🇴', 'BG': '🇧🇬',
  'AL': '🇦🇱', 'ME': '🇲🇪', 'SI': '🇸🇮', 'NO': '🇳🇴',
  'SE': '🇸🇪', 'FI': '🇫🇮', 'DK': '🇩🇰', 'IS': '🇮🇸',
  'LK': '🇱🇰', 'VN': '🇻🇳', 'KH': '🇰🇭', 'ID': '🇮🇩',
  'SG': '🇸🇬', 'MY': '🇲🇾', 'PH': '🇵🇭', 'CN': '🇨🇳',
  'KR': '🇰🇷', 'JM': '🇯🇲', 'CU': '🇨🇺', 'DO': '🇩🇴',
  'CR': '🇨🇷', 'FJ': '🇫🇯', 'PF': '🇵🇫', 'MT': '🇲🇹',
  'GE': '🇬🇪', 'UN': '🌍',
};

// Destination name → country code
const DEST_CODES: Record<string, string> = {
  'יוון': 'GR', 'greece': 'GR', 'אתונה': 'GR', 'סנטוריני': 'GR', 'כרתים': 'GR', 'מיקונוס': 'GR', 'רודוס': 'GR',
  'איטליה': 'IT', 'italy': 'IT', 'רומא': 'IT', 'מילאנו': 'IT', 'ונציה': 'IT', 'פירנצה': 'IT', 'סיציליה': 'IT', 'סרדיניה': 'IT', 'נאפולי': 'IT', 'אמלפי': 'IT',
  'צרפת': 'FR', 'france': 'FR', 'פריז': 'FR', 'ניס': 'FR', 'מרסיי': 'FR', 'ליון': 'FR',
  'ספרד': 'ES', 'spain': 'ES', 'ברצלונה': 'ES', 'מדריד': 'ES', 'איביזה': 'ES', 'מיורקה': 'ES', 'מלגה': 'ES', 'טנריף': 'ES',
  'פורטוגל': 'PT', 'portugal': 'PT', 'ליסבון': 'PT', 'פורטו': 'PT',
  'תורכיה': 'TR', 'turkey': 'TR', 'איסטנבול': 'TR', 'אנטליה': 'TR', 'בודרום': 'TR', 'קפדוקיה': 'TR',
  'קפריסין': 'CY', 'cyprus': 'CY', 'לרנקה': 'CY', 'פאפוס': 'CY', 'איה נאפה': 'CY',
  'תאילנד': 'TH', 'thailand': 'TH', 'בנגקוק': 'TH', 'פוקט': 'TH', 'קו סמוי': 'TH', "צ'יאנג מאי": 'TH',
  'יפן': 'JP', 'japan': 'JP', 'טוקיו': 'JP', 'קיוטו': 'JP', 'אוסקה': 'JP',
  'הודו': 'IN', 'india': 'IN', 'גואה': 'IN', 'דלהי': 'IN', 'מומבאי': 'IN',
  'מצרים': 'EG', 'egypt': 'EG', 'שארם א-שייח': 'EG', 'שארם': 'EG', 'קהיר': 'EG', 'הורגדה': 'EG',
  'ירדן': 'JO', 'jordan': 'JO', 'עמאן': 'JO', 'פטרה': 'JO',
  'מרוקו': 'MA', 'morocco': 'MA', 'מרקש': 'MA',
  'דובאי': 'AE', 'אמירויות': 'AE', 'abu dhabi': 'AE', 'אבו דאבי': 'AE', 'uae': 'AE',
  'מלדיביים': 'MV', 'maldives': 'MV',
  'סיישל': 'SC', 'seychelles': 'SC',
  'מאוריציוס': 'MU', 'mauritius': 'MU',
  'זנזיבר': 'TZ', 'טנזניה': 'TZ', 'tanzania': 'TZ',
  'קניה': 'KE', 'kenya': 'KE',
  'דרום אפריקה': 'ZA', 'south africa': 'ZA', 'קייפטאון': 'ZA',
  'ארה"ב': 'US', 'ארהב': 'US', 'usa': 'US', 'ניו יורק': 'US', "לוס אנג'לס": 'US', 'מיאמי': 'US', 'לאס וגאס': 'US', 'הוואי': 'US', 'סן פרנסיסקו': 'US', 'אורלנדו': 'US',
  'קנדה': 'CA', 'canada': 'CA', 'טורונטו': 'CA', 'ונקובר': 'CA',
  'מקסיקו': 'MX', 'mexico': 'MX', 'קנקון': 'MX',
  'ברזיל': 'BR', 'brazil': 'BR', 'ריו': 'BR',
  'ארגנטינה': 'AR', 'argentina': 'AR', 'בואנוס איירס': 'AR',
  'קולומביה': 'CO', 'colombia': 'CO',
  'פרו': 'PE', 'peru': 'PE',
  'אוסטרליה': 'AU', 'australia': 'AU', 'סידני': 'AU', 'מלבורן': 'AU',
  'ניו זילנד': 'NZ', 'new zealand': 'NZ',
  'אנגליה': 'GB', 'בריטניה': 'GB', 'לונדון': 'GB', 'england': 'GB', 'uk': 'GB',
  'גרמניה': 'DE', 'germany': 'DE', 'ברלין': 'DE', 'מינכן': 'DE',
  'הולנד': 'NL', 'netherlands': 'NL', 'אמסטרדם': 'NL',
  "צ'כיה": 'CZ', 'czech': 'CZ', 'פראג': 'CZ',
  'אוסטריה': 'AT', 'austria': 'AT', 'וינה': 'AT',
  'שוויץ': 'CH', 'switzerland': 'CH', 'ציריך': 'CH',
  'קרואטיה': 'HR', 'croatia': 'HR', 'דוברובניק': 'HR',
  'הונגריה': 'HU', 'hungary': 'HU', 'בודפשט': 'HU',
  'פולין': 'PL', 'poland': 'PL', 'קרקוב': 'PL', 'ורשה': 'PL',
  'רומניה': 'RO', 'romania': 'RO', 'בוקרשט': 'RO',
  'בולגריה': 'BG', 'bulgaria': 'BG',
  'אלבניה': 'AL', 'albania': 'AL',
  'מונטנגרו': 'ME', 'montenegro': 'ME',
  'סלובניה': 'SI', 'slovenia': 'SI',
  'נורבגיה': 'NO', 'norway': 'NO',
  'שבדיה': 'SE', 'sweden': 'SE',
  'פינלנד': 'FI', 'finland': 'FI',
  'דנמרק': 'DK', 'denmark': 'DK', 'קופנהגן': 'DK',
  'איסלנד': 'IS', 'iceland': 'IS',
  'סרי לנקה': 'LK', 'sri lanka': 'LK',
  'וייטנאם': 'VN', 'vietnam': 'VN',
  'קמבודיה': 'KH', 'cambodia': 'KH',
  'באלי': 'ID', 'אינדונזיה': 'ID', 'indonesia': 'ID',
  'סינגפור': 'SG', 'singapore': 'SG',
  'מלזיה': 'MY', 'malaysia': 'MY',
  'פיליפינים': 'PH', 'philippines': 'PH',
  'סין': 'CN', 'china': 'CN', "בייג'ינג": 'CN', 'שנגחאי': 'CN',
  'דרום קוריאה': 'KR', 'korea': 'KR', 'סיאול': 'KR',
  "ג'מייקה": 'JM', 'jamaica': 'JM',
  'קובה': 'CU', 'cuba': 'CU',
  'דומיניקנה': 'DO', 'dominican': 'DO', 'פונטה קאנה': 'DO',
  'קוסטה ריקה': 'CR', 'costa rica': 'CR',
  "פיג'י": 'FJ', 'fiji': 'FJ',
  'טהיטי': 'PF', 'tahiti': 'PF', 'בורה בורה': 'PF',
  'מלטה': 'MT', 'malta': 'MT',
  "ג'ורג'יה": 'GE', 'georgia': 'GE', 'טביליסי': 'GE', 'באטומי': 'GE',
};

export function getDestFlag(dest?: string): string {
  if (!dest) return '';
  const lower = dest.toLowerCase().trim();
  if (DEST_CODES[lower]) return FLAGS[DEST_CODES[lower]] || '🌍';
  for (const [key, code] of Object.entries(DEST_CODES)) {
    if (lower.includes(key) || key.includes(lower)) return FLAGS[code] || '🌍';
  }
  return '🌍';
}
